---
- name: Show BGP Neighbors
  hosts: routers
  gather_facts: false


  tasks:
    - name: BGP Neighbors
      raw: "show ip bgp neighbors"
      register: output #register the output in a variable named output

    - name: Printing Output
      debug: var=output.stdout_lines  #print the variable at the console line by line

...


# Description:
# Run show commands using raw module
# https://docs.ansible.com/ansible/2.5/modules/raw_module.html

# Command to run:
# ansible-playbook -i ./hosts ./show_bgp_neighbors.yaml -u u1 -k
# both hosts and yaml file are in the current working directory